### ISSUE TITLE
Possible problem with calculating distances

### ISSUE THREAD

**Issue by TPReal** [the-abe-train/globle#7] opened 2022-02-05 21:41 UTC
Please take a look at the screenshot. How is it possible that France is furthest from Netherlands of all my guesses? Looks completely invalid.

Additional information: I opened the game a day or two ago, guessed France, Poland and something more, and I think the colors were as they are now, Poland quite dark and France very pale. Then I found the game open in a tab today, I refreshed the tab because I expected the game resets maybe with a new country every day so I'll get blank globe again, but this didn't happen, my guesses remained there. I made some more guesses until I figured out Netherlands. So either distance calculation between France and Netherlands is completely wrong, or games from two different days got mixed up.

![image](https://user-images.githubusercontent.com/115690/152659864-14745540-d8fa-468a-8eef-5ae906a2ec5a.png)

**Comment by the-abe-train** [comment] 2022-02-05 23:29
Duplicate of #6
I have identified the issue, pushing a change soon.

**Closed by the-abe-train** 2022-02-05 23:29 UTC
